version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
      - ./db/config/my.cnf:/etc/mysql/conf.d/my.cnf
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    depends_on:
      - db
